"""
Application layer DTOs.
Data Transfer Objects for API requests and responses.
"""

from .base_dto import *
from .client_dto import *
from .user_dto import *
from .project_dto import *
from .task_dto import *
from .time_entry_dto import *
from .invoice_dto import *
from .share_dto import *

__all__ = [
    # Base DTOs
    "BaseDTO",
    "RequestDTO", 
    "ResponseDTO",
    "CreateRequestDTO",
    "UpdateRequestDTO",
    "ListRequestDTO",
    "FilterRequestDTO",
    "SearchRequestDTO",
    "BulkRequestDTO",
    "BulkResponseDTO",
    "ListResponseDTO",
    "HealthCheckResponseDTO",
    "ErrorResponseDTO",
    "ValidationErrorResponseDTO",
    "StatsResponseDTO",
    "TimestampMixin",
    "OwnerMixin",
    "TagsMixin",
    "NotesMixin",
    "SortOrder",
    "ExportFormat",
    
    # Client DTOs
    "ContactInfoRequestDTO",
    "ContactInfoResponseDTO",
    "CreateClientRequestDTO",
    "UpdateClientRequestDTO", 
    "UpdateClientBillingRequestDTO",
    "ListClientsRequestDTO",
    "SearchClientsRequestDTO",
    "ClientStatsResponseDTO",
    "ClientResponseDTO",
    "ClientSummaryResponseDTO",
    "ClientActivityResponseDTO",
    "ClientRevenueResponseDTO",
    "BulkUpdateClientsRequestDTO",
    "ArchiveClientRequestDTO",
    "ClientAnalyticsResponseDTO",
    "ClientHealthScoreResponseDTO",
    
    # User DTOs
    "CreateUserRequestDTO",
    "UpdateUserRequestDTO",
    "UpdateUserPreferencesRequestDTO",
    "UpdateBillingInfoRequestDTO",
    "ChangePasswordRequestDTO",
    "ListUsersRequestDTO",
    "UserPreferencesResponseDTO",
    "UserStatsResponseDTO",
    "UserResponseDTO",
    "UserProfileResponseDTO",
    "AuthUserResponseDTO",
    "LoginRequestDTO",
    "RegisterRequestDTO",
    "RefreshTokenRequestDTO",
    "ForgotPasswordRequestDTO",
    "ResetPasswordRequestDTO",
    "VerifyEmailRequestDTO",
    "UserActivityResponseDTO",
    "UserProductivityResponseDTO",
    "UserTimeTrackingStatsDTO",
    
    # Project DTOs
    "ProjectStatus",
    "ProjectMemberRole", 
    "BillingType",
    "ProjectMemberRequestDTO",
    "ProjectMemberResponseDTO",
    "ProjectBudgetResponseDTO",
    "ProjectTimeStatsDTO",
    "CreateProjectRequestDTO",
    "UpdateProjectRequestDTO",
    "UpdateProjectStatusRequestDTO",
    "AddProjectMemberRequestDTO",
    "UpdateProjectMemberRequestDTO",
    "ListProjectsRequestDTO",
    "SearchProjectsRequestDTO",
    "ProjectTimeRangeRequestDTO",
    "ProjectStatsResponseDTO",
    "ProjectResponseDTO",
    "ProjectSummaryResponseDTO",
    "ProjectActivityResponseDTO",
    "ProjectReportResponseDTO",
    "BulkUpdateProjectsRequestDTO",
    "ArchiveProjectRequestDTO",
    "ProjectAnalyticsResponseDTO",
    
    # Task DTOs
    "TaskPriority",
    "TaskStatus",
    "TaskAttachmentRequestDTO",
    "TaskAttachmentResponseDTO", 
    "TaskCommentRequestDTO",
    "TaskCommentResponseDTO",
    "TaskTimeStatsDTO",
    "CreateTaskRequestDTO",
    "UpdateTaskRequestDTO",
    "UpdateTaskStatusRequestDTO",
    "AssignTaskRequestDTO",
    "MoveTaskRequestDTO",
    "ListTasksRequestDTO",
    "SearchTasksRequestDTO",
    "TaskTimeRangeRequestDTO",
    "TaskResponseDTO",
    "TaskSummaryResponseDTO",
    "TaskActivityResponseDTO",
    "TaskBoardResponseDTO",
    "TaskReportResponseDTO",
    "BulkUpdateTasksRequestDTO",
    "BulkMoveTasksRequestDTO",
    "TaskAnalyticsResponseDTO",
    "TaskDependencyRequestDTO",
    "TaskDependencyResponseDTO",
    
    # Time Entry DTOs
    "TimeEntryStatus",
    "TimeEntryType",
    "StartTimerRequestDTO",
    "StopTimerRequestDTO",
    "CreateTimeEntryRequestDTO",
    "UpdateTimeEntryRequestDTO",
    "SubmitTimeEntryRequestDTO",
    "ApproveTimeEntryRequestDTO",
    "RejectTimeEntryRequestDTO",
    "ListTimeEntriesRequestDTO",
    "SearchTimeEntriesRequestDTO",
    "TimeEntryReportRequestDTO",
    "RunningTimerResponseDTO",
    "TimeEntryResponseDTO",
    "TimeEntrySummaryResponseDTO",
    "TimeEntryStatsResponseDTO",
    "TimeEntryReportResponseDTO",
    "DailyTimeStatsDTO",
    "BulkUpdateTimeEntriesRequestDTO",
    "BulkDeleteTimeEntriesRequestDTO",
    "TimeTrackingAnalyticsResponseDTO",
    "ExportTimeEntriesRequestDTO",
    
    # Invoice DTOs
    "InvoiceStatus",
    "InvoiceItemType",
    "PaymentStatus",
    "PaymentMethod",
    "InvoiceItemRequestDTO",
    "InvoiceItemResponseDTO",
    "PaymentRequestDTO",
    "PaymentResponseDTO",
    "InvoiceAddressDTO",
    "CreateInvoiceRequestDTO",
    "CreateInvoiceFromTimeRequestDTO",
    "UpdateInvoiceRequestDTO",
    "SendInvoiceRequestDTO",
    "ListInvoicesRequestDTO",
    "SearchInvoicesRequestDTO",
    "InvoiceTotalsResponseDTO",
    "InvoiceResponseDTO",
    "InvoiceSummaryResponseDTO",
    "InvoiceStatsResponseDTO",
    "InvoiceReportResponseDTO",
    "BulkUpdateInvoicesRequestDTO",
    "BulkSendInvoicesRequestDTO",
    "InvoiceAnalyticsResponseDTO",
    "ExportInvoicesRequestDTO",
    
    # Share DTOs
    "ShareResourceType",
    "ShareAccessLevel",
    "ShareStatus",
    "CreateShareRequestDTO",
    "UpdateShareRequestDTO",
    "AccessSharedResourceRequestDTO",
    "RevokeShareRequestDTO",
    "ListSharesRequestDTO",
    "ShareAnalyticsRequestDTO",
    "ShareResponseDTO",
    "ShareSummaryResponseDTO",
    "SharedResourceResponseDTO",
    "ShareAccessLogResponseDTO",
    "ShareStatsResponseDTO",
    "ShareAnalyticsResponseDTO",
    "BulkUpdateSharesRequestDTO",
    "BulkRevokeSharesRequestDTO",
    "ExportShareAnalyticsRequestDTO",
    "ShareTemplateRequestDTO",
    "ShareTemplateResponseDTO",
]